# ls-lint 設定ファイル
# https://ls-lint.org/2.x/configuration/the-basics.html

ls:
  # すべてのディレクトリは kebab-case または Next.js の特別なパターンを使用
  .dir: regex:^[a-z][a-z0-9]*(-[a-z0-9]+)*$|^\([a-z][a-z0-9-]*\)$|^_[a-z][a-z0-9-]*$ # kebab-case, (route-groups), or _private

  # App Router - Next.js の特別なファイルとルーティング（パス内のどこにでも適用）
  "**/app/**":
    .tsx: regex:^(page|layout|loading|error|not-found|template|default)$|^[A-Z][a-zA-Z0-9]*$ # Next.js ファイル または PascalCase コンポーネント
    .ts: regex:^(route|middleware|proxy)$|^use[A-Z][a-zA-Z0-9]*Store$|^use[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9]*(-[a-z0-9]+)*$ # route ファイル、ストア、フック、または kebab-case

  # Features ディレクトリ（再帰的: features 配下のすべてのネストされたパスに適用）
  "**/features/**":
    .tsx: PascalCase # コンポーネント
    .ts: regex:^use[A-Z][a-zA-Z0-9]*Store$|^use[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9]*(-[a-z0-9]+)*$|^index$ # ストア、フック、kebab-case ユーティリティ、または index
    .stories.tsx: PascalCase

  # Shared/Components ディレクトリ - より具体的なサブディレクトリより前に配置する必要がある
  "**/components/**":
    .tsx: PascalCase
    .ts: regex:^use[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9]*(-[a-z0-9]+)*$|^index$ # フック、kebab-case ユーティリティ、または index
    .stories.tsx: PascalCase

  "**/shared/**":
    .tsx: PascalCase
    .ts: regex:^use[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9]*(-[a-z0-9]+)*$|^index$ # フック、kebab-case ユーティリティ、または index
    .stories.tsx: PascalCase

  # 特定のサブディレクトリ - shared/components の後に配置してルールを上書き
  # Stores ディレクトリ（Zustand）
  "**/stores/**":
    .ts: regex:^use[A-Z][a-zA-Z0-9]*Store$|^index$ # useAuthStore, useCartStore, または index

  # Hooks ディレクトリ
  "**/hooks/**":
    .ts: regex:^use[a-z][a-zA-Z0-9]*$|^index$ # useAuth, useLocalStorage, または index

  # Lib ディレクトリ（ユーティリティとヘルパー）
  "**/lib/**":
    .ts: kebab-case

  # Utils ディレクトリ
  "**/utils/**":
    .ts: kebab-case

  # Types ディレクトリ - kebab-case で -type または -types サフィックスを必須とする
  "**/types/**":
    .ts: regex:^[a-z][a-z0-9]*(-[a-z0-9]+)*-(type|types)$|^index$ # kebab-case で -type または -types で終わる、または index

  # Constants ディレクトリ
  "**/constants/**":
    .ts: kebab-case

  # Styles ディレクトリ
  "**/styles/**":
    .css: kebab-case

  # Public ディレクトリ
  public:
    .dir: kebab-case

  # ルートレベルと src ディレクトリ
  .:
    .tsx: PascalCase
    .ts: regex:^use[A-Z][a-zA-Z0-9]*Store$|^use[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9]*(-[a-z0-9]+)*$|^index$
    .js: kebab-case
    .json: kebab-case
    .md: kebab-case

  src:
    .tsx: PascalCase
    .ts: regex:^use[A-Z][a-zA-Z0-9]*Store$|^use[a-z][a-zA-Z0-9]*$|^[a-z][a-z0-9]*(-[a-z0-9]+)*$|^index$

ignore:
  - node_modules
  - .next
  - dist
  - build
  - .git
  - .vscode
  - coverage
  - .turbo
  - out
